name: Deploy to Dev Environment
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ secrets.EC2_SSH_KEY }} > id_rsa
          chmod 400 id_rsa
          ssh -i ~/id_rsa -o StrictHostKeyChecking=no ubuntu@13.126.55.15 << 'EOF'
          #!/bin/bash
          cd /home/ubuntu/monolithic-app-cicd
          git pull origin master
          pnpm install
          pm2 restart all
          EOF
      - name: Clean up SSH key
        run: rm -f id_rsa
        if: always() # Ensure cleanup runs even if previous steps fail
      - name: Notify Deployment Success
        run: echo "Deployment to Dev Environment successful!"
        if: success() # Only run if the deployment was successful
