name: Deploy to Dev Environment
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > id_rsa.pem
          chmod 700 id_rsa.pem
          ssh -i ./id_rsa.pem -o StrictHostKeyChecking=no ubuntu@13.126.55.15 << 'EOF'
          #!/bin/bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
          nvm use 20
          cd /home/ubuntu/monolithic-app-cicd
          git pull origin master
          pnpm install
          pm2 restart all
          EOF
      - name: Clean up SSH key
        run: rm -f id_rsa
        if: always() # Ensure cleanup runs even if previous steps fail
      - name: Notify Deployment Success
        run: echo "Deployment to Dev Environment successful!"
        if: success() # Only run if the deployment was successful
